// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models
{
    [Table("Item")]
    public partial class Item
    {
        public Item()
        {
            ItemBranches = new HashSet<ItemBranch>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Name { get; set; }
        public int? Price { get; set; }

        [InverseProperty("Item")]
        public virtual ICollection<ItemBranch> ItemBranches { get; set; }
    }
}