// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models
{
    [Table("ItemBranch")]
    public partial class ItemBranch
    {
        [Key]
        public int ItemId { get; set; }
        [Key]
        public int BranchId { get; set; }
        public int? Quantity { get; set; }

        [ForeignKey("BranchId")]
        [InverseProperty("ItemBranches")]
        public virtual Branch Branch { get; set; }
        [ForeignKey("ItemId")]
        [InverseProperty("ItemBranches")]
        public virtual Item Item { get; set; }
    }
}